### ISSUE TITLE
Mrlcomm defined more than once.

### ISSUE THREAD

**Issue by sanjotSingh** [MyRobotLab/mrlcomm#1]
Hi, i am a high school student and i am currently working on inmoov hand project. i was trying to upload MRLcomm to arduino but i got an error saying that MRLcomm have been defined twice. I am working on Ubuntu Linux(64bit). I have the latest version of MyRobotLab and Arduino. Please notify me if you need more information on the issue.

**Comment by kwatters** [comment]
What version of the Arduino IDE are you using?  I know version 1.6.8 works, but that's a slightly older version.

**Comment by supertick** [comment]
Always use the MrlComm version which came with Mrl - it can be found of the Arduino tab when swinggui is running
